default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>

development:
  <<: *default
  database: ac_brasil_development


test:
  <<: *default
  database: ac_brasil_test


production:
  <<: *default
  database: ac_brasil_production
  username: ac_brasil
  password: <%= ENV["AC_BRASIL_DATABASE_PASSWORD"] %>
